- name: ssh deploy to server
  uses: Gabo-p/ssh-deploy-to-server@v1.0.7
  with:
    # Private key part of an SSH key pair
    SSH_PRIVATE_KEY: 
    # Remote host
    REMOTE_HOST: 
    # Remote user
    REMOTE_USER: 
    # Remote port
    REMOTE_PORT: # optional, default is 22
    # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
    SOURCE: # optional, default is 
    # Target directory
    TARGET: # optional, default is 
    # Arguments to pass to rsync
    ARGS: # optional, default is -rlgoDzvc -i
    # An array of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5 
    SSH_CMD_ARGS: # optional, default is -o StrictHostKeyChecking=no
    # paths to exclude separated by `,`, ie: `/dist/, /node_modules/`
    EXCLUDE: # optional, default is 
    # Script to run on host machine before rsync
    SCRIPT_BEFORE: # optional, default is 
    # Script to run on host machine after rsync
    SCRIPT_AFTER: # optional, default is 
          
